#!/bin/bash

echo "Setting up Vercel Postgres for production..."
echo ""
echo "1. Go to https://vercel.com and navigate to your project 'scex-application-suite'"
echo "2. Click on 'Storage' tab"
echo "3. Click 'Create Database' and select 'Postgres'"
echo "4. Name it 'scex-postgres' and click Create"
echo ""
echo "5. Once created, go to Settings > Environment Variables"
echo "6. The POSTGRES_URL variable should be automatically created"
echo "7. Copy the POSTGRES_URL value"
echo "8. Create/Update DATABASE_URL with the same value for Production environment"
echo ""
echo "9. Then run: vercel env pull"
echo "10. Then run the Prisma migration: npx prisma migrate deploy"
echo ""
echo "Alternatively, run these commands:"
echo "  vercel env rm DATABASE_URL production"
echo "  vercel env add DATABASE_URL production"
echo "  (paste the POSTGRES_URL value when prompted)"
echo ""
